name: 'Leaky Abstractions'
url: 'https://leakyabstractions.dev'
description: 'Software engineering, architecture and computer science deep dives. With a focus on game dev and embedded systems.'

author:
    name: 'mrbandler'
    url: 'https://github.com/mrbandler'
    email: 'mrbandler@leakyabstractions.dev'
    icon: 'fa-brands fa-github'
    sameAs:
        - 'https://mrbandler.dev'

publisher:
    name: 'Leaky Abstractions'
    url: 'https://leakyabstractions.dev'
    sameAs:
        - 'https://github.com/leaky-abstractions'
        - 'https://youtube.com/@leakyabstractions'
